// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfshgepiqrgpvqorohoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmc2hnZXBpcXJncHZxb3JvaG9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzM4MDYsImV4cCI6MjA1OTg0OTgwNn0.EoyBlV9Smj8_h0n_pdsi6MyRUO-W1ZLy2fUOgt0mA00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);